### ISSUE TITLE
Meetup ??/2016 - @lmduc - Find ruby methods' definitions

### ISSUE THREAD

**Issue by lmduc** [ruby-vietnam/meetup#100]
I'll talk about:
- Some basic ways to find ruby methods' definitions in run time
- Advantages and disadvantages of those ways

**Comment by runlevel5** [comment]
👍

**Comment by xjaokjng** [comment]
wow like like

**Comment by phthhieu** [comment]
💯

**Comment by andyduong1920** [comment]
:+1:

**Comment by runlevel5** [comment]
Speaker vì lí do đột xuất nên không về VN đc, nên xin khất lại lần sau
