### ISSUE TITLE
Meetup 08/2016 - @khacanh - Tune your Rails application

### ISSUE THREAD

**Issue by khacanh** [ruby-vietnam/meetup#101]
I will cover some basic steps to fine tune your app: 
- Start with a good performance measuring tool
- Pinpoint the source of the performance issues
- Start with "low-hanging fruit" improvements
- It's rarely because of the Ruby code
- Some times it needs major system changes

Here is the link to the presentation: 

https://docs.google.com/presentation/d/1DjQ6tF8T8AQhuaT_AOGO4wvCsqCZ_CZXhl81rYfXEsc/edit#slide=id.g164fe979ff_0_796

Thank you!

**Comment by mymai91** [comment]
👍
