### ISSUE TITLE
Meetup 08/2016 - @kimhieu - JWT basic and How to integrate it with Rails (Grape)

### ISSUE THREAD

**Issue by tkhieu** [ruby-vietnam/meetup#102]
Hi, folks
I would like to list  the outline of the talk
1. Talk about JWT, Some important points from `rfc7519`
2. Integrate it with Grape to validate current user and do mobile authentication.

https://docs.google.com/presentation/d/1vHo2woFh1cCAdHCpLpX2YeKg6QMDXYs-FUM0zqUiORM/

**Comment by andyduong1920** [comment]
:+1:

**Comment by mymai91** [comment]
👍
