### ISSUE TITLE
Meetup 10/2016 - Ruby Exceptions - @nhattan

### ISSUE THREAD

**Issue by runlevel5** [ruby-vietnam/meetup#105]
After this session, you would know what Ruby exception is and how to get the best out of it to make a better Ruby app.

**Comment by runlevel5** [comment]
👍

**Comment by leo-le-07** [comment]
👍

**Comment by thieunv90** [comment]
👍

**Comment by dereknguyen269** [comment]
👍

**Comment by nhattan** [comment]
Thanks all for your thumbs up!
Here's my presentation: https://goo.gl/BPVM8k
