### ISSUE TITLE
Meetup 12/2016 - Build a web app with Rails, React and Redux - @khacanh

### ISSUE THREAD

**Issue by khacanh** [ruby-vietnam/meetup#106]
Hi everyone, in this meetup I'll talk about rails + react + redux, it's actually more on the client-side. 
Below is the proposed template, it is subject to change as the slides are updated. 

### Server - client architecture
+ Separate responsibility
+ Separate domain of expertise
+ Scale independently
+ Rails 5 has the api-only option

### Why ReactJS
+ Learning curve
+ Community
+ Reuse for mobile platform (React Native?)

### React vs. DOM manipulation
+ Automatic view update
  - Just change the data, react will renders UI for you
+ Component-based
  - Encapsulate component, then compose them to build complex UIs
+ Asynchronous and direct dom manipulation
(Comparison of jQuery, vanilla JS and ReactJS)

### Why redux
+ Internal state explosion with pure ReactJS
+ Internal state is the root of all evil?
+ Unidirectional dataflow
+ Single source of truth
+ Shared logic between web and mobile
(Show pure React code vs Redux code)

### Different from a full-stack app
+ Architectural differences
+ Authentication strategy
+ Asset pipelines
+ CORS
+ Convention over configuration

### Learning curve
+ React is pretty minimal
+ Learn just enough to get started
+ JSX looks weird at the beginning, BabbelJS to the rescue
+ Redux code is concise, get ready for some new JS syntaxes
+ Understand the core differences, get used to the new dataflow

### Choose a boilerplate app
+ Convention over configuration
+ React redux starter kit
+ create-react-app

### Demo
+ Server api with Rails 5
+ Web app with ReactJS and Redux
+ Mobile app with ReactNative and Redux

**Comment by runlevel5** [comment]
Wow, seems a bit full on, keen to see how mobile app is built 👍

**Comment by khacanh** [comment]
Yeah, I'll just focus on the high-level stuff, and may trim down a bit

**Comment by tkhieu** [comment]
Eager to attend this topic.

**Comment by tucq88** [comment]
A lot of stuff, don't know how could you cover them all in one talk. Do we have livestream or video recording for this meetup ?

**Comment by runlevel5** [comment]
@tucq88 I would not do any livestream because it is not our priority atm. The exp would be so poor.

I agree it is a big task to cover everything, I would not expect this would happen within 15'. It is more likely 30' talk

**Comment by revskill10** [comment]
Just be concise and you can cover these things. (Make at least assumption on audience as possible)
