### ISSUE TITLE
Meetup 4/2017 - Overview / Intro to CoderSchool's Ruby/Rails curriculum - Harley Trung

### ISSUE THREAD

**Issue by runlevel5** [ruby-vietnam/meetup#107]
Harley Trung is teacher/developer/co-founder of [CoderSchool](https://www.facebook.com/coderschoolvn/).

The school provides one of many quality Ruby courses in Vietnam and has slowly gain reputation in powering students who have no knowledge of Ruby/Rails to be proficient in the language / framework. Many grads are now joining the industry.

So if you are interested in learning Ruby/Rails, come over to learn what the school has to offer. 

-----

Harley Trung là giảng viên / lập trình viên / đồng sáng lập của trường CoderSchool.

Hiện trường đang khai giảng thường xuyên các khoá đào tạo Ruby và Rails tại VN, có rất nhiều lứa tốt nghiệp của trường đã tìm được việc làm tại các công ty phần mềm tại VN.

Nếu bạn quan tâm về một tương lai nghề nghiệp với Ruby và Rails thì hãy mau chóng đăng ký tham gia để tìm hiểu khoá học chất lượng này.

Anh Harley Trung sẽ tận tình trả lời tất cả thắc mắc của các bạn trong khuôn khổ của meetup lần này.

Rất khuyến khích các bạn sinh viên khoá công nghệ thông tin / phần mềm hoặc các bạn dev hiện đang làm mảng khác nhưng muốn chuyển qua làm Ruby.

**Comment by tucq88** [comment]
Một trong những khoá học thực tế, hiếm hoi và chất lượng nhất cho dev ở Vietnam lúc này.

**Comment by giangbimin** [comment]
awesome!

**Comment by PrimeTimeTran** [comment]
Looking forward to seeing it~!

**Comment by kiendt07** [comment]
Best thing that happened in my college life. Also Harley is the best teacher, ever!

**Comment by thuanpt** [comment]
HN ko có! tiếc quá
