### ISSUE TITLE
Meetup 4/2017 - Extend Rails app with Sinatra - @kimquy

### ISSUE THREAD

**Issue by sirius248** [ruby-vietnam/meetup#108]
Abstract: In this talk, I will walk you through a simple ruby gem which built with Sinatra. And it can be easily embedded inside any Rails app. Then I will walk you through the internal of Ruby on Rails source code to show you how everything actually connect and work the way it's. By understanding more how any Rails application work under the hood. In the end, there will be a short demo.

**Comment by runlevel5** [comment]
Một chút survey mọi người, chủ để này thực sự khá là hay và có thể đào sâu. Mình muốn bài nói đc dẫn dắt theo hướng mở để mọi người có cơ hội tham gia đặt câu hỏi hoặc trả lời. Mình muốn hỏi rằng ở chủ để trên thì mọi người quan tâm mảng nào nhất?

Riêng mình thì mình quan tâm về phần tích hợp gem này với một app có sẵn, thực sự có nhiều cách vd rails engine vs rack mount, nhược và lợi của mỗi cách và cũng quan tâm về cách viết integration test cho gem

Để giúp @kimquy chuẩn bị kĩ bài nói thì mong mọi người cho phản hồi.

**Comment by nctruong** [comment]
Thanks for sharing with us. That's pretty enough for a presentation. However, according @joneslee85 we can dig deeply into the matter. How about using command line for a gem? is it like the rails task?

**Comment by runlevel5** [comment]
@nctruong the topic would be about building a gem with Sinatra; it is not necessary for rails. Thus it opens for discussion how one gem could be integrated into rails or rack-based app.

I don't think the presenter want to talk about a simple CLI gem or a rake tasks for an existing rails app. If time allows, I think he could cover how to integrate a gem with rails. I leave it to him.
