### ISSUE TITLE
Meetup ? - <họ và tên> (@github_handler) - Cơ bản về MiniTest

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/meetup#15]
MiniTest là thư viện test mặc định của Ruby 1.9 đổ về, nhưng thực sự là rất ít người biết sử dụng hết công năng của thư viện này vì có lẽ đa số dùng RSpec khi phát triển Rails app. Bài nói sau sẽ giới thiệu cho bạn cách sử dụng assertion và spec matcher của MiniTest.

**Comment by pddo** [comment]
:+1:

**Comment by joneslee85** [comment]
Vẫn chỉ là gợi ý chủ đề, có ai muốn nói bài này không?
