### ISSUE TITLE
Meetup ? - <họ và tên> (@github_handler) - Các mẹo làm việc hiệu quả

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/meetup#16]
Một ngày cũng chỉ có 24 giờ, và 8 tiếng đi làm. Bạn có bao giờ tự hỏi làm cách nào để tối ưu hoá xử lý công việc để bạn có nhiều thời gian trống để đọc, học và giải trí không? Bài nói sẽ chia sẻ một số kinh nghiệm và thủ thuật để lên lịch, quản lý thời gian, làm việc theo nhóm, họp hành và trau dồi thêm kiến thức theo phương pháp thực dụng và hiệu quả.

**Comment by pddo** [comment]
:+1:

**Comment by joneslee85** [comment]
Vẫn chỉ là gợi ý chủ đề, có ai muốn nói bài này không?
