### ISSUE TITLE
Meetup 2/2016 - Sam Saffron(@samsaffron) - Profiling Rails app like a pro!

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/meetup#18]
Sau 4 năm qua từ bản 1.8 đến nay, bản 2.1.2, Ruby đã cải thiện đáng kể phần tốc độ với engine GC mới. Nhưng thực sự bạn có thể tối ưu hoá thêm ít nhất 20%-30% hiệu suất bằng cách tune Ruby. Thêm vào nữa nếu app bạn bị chậm hay leak thì bài nói sau cũng sẽ hướng dẫn bạn một số thủ thuật để đo và cải thiện.

Diễn giả Sam Saffrone là kỹ sư của sản phẩm Discourse nổi tiếng, anh dầy dạn kn trong việc tuning Rails app, không ai phủ nhận đc điều đó khi đã nghe qua một vài bài nói của anh về chủ đề GC. 

Hãy bầu chọn ngay cho anh nếu bạn muốn anh làm khách mời siêu sao cho meetup :)

**Comment by suonlight** [comment]
:+1:

**Comment by joneslee85** [comment]
Cái này chỉ là gợi ý thôi, có ai muốn làm bài này thì cho mình biết
