### ISSUE TITLE
Meetup ?? - Toby Hede (@tobyhede) - Intro to Volts

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/meetup#19]
Toby Hede (@tobyhede) là một trong những kỹ sư máu mặt của cộng đồng Ruby Sydney. Mình có gợi ý anh làm một bài nói online cho meetup và anh đồng ý. Anh sẽ giới thiệu cho các bạn framework Volts.

Các mem nào quan tâm thì reply lại với :+1:, nếu có trên 5 replies thì mình sẽ chính thức chốt với anh ấy.

**Comment by stnguyen** [comment]
:+1:
