### ISSUE TITLE
Meetup tháng 11 - Luca Guidi (@jodosha) - Giới thiệu Lotus Framework

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/meetup#24]
Luca là tác giả của Web Framework Lotus, Lotus là thành quả 10 năm của anh, framework này còn rất mới mẻ với cộng đồng Ruby. Cái hay của framework này là anh đã nghiên cứu kỹ các khuyết điểm của Rails để tạo ra một framework mới đơn giản, cực nhanh, hoàn toàn cô lập, thể hiện các business logic, phân cách các lớp, vv. Anh sẽ làm một bài giới thiệu framework tuyệt vời này nếu mọi người vote cho anh

**Comment by stnguyen** [comment]
:+1:  lần này có không ạ?

**Comment by joneslee85** [comment]
@stnguyen nếu lần này khu vực HN mạng tốt thì có thể

**Comment by joneslee85** [comment]
Anh Luca oke về làm một bài online, vì mạng lần này tốt nên quyết định thử nghiệm

**Comment by hoang1417** [comment]
:+1: it's great hearing about Lotus

**Comment by joneslee85** [comment]
Mạng AAG vẫn chập chờn nên đành hoãn lại tiếp, haizzz

**Comment by huynhquancam** [comment]
:+1: lót dép ngồi hóng

**Comment by joneslee85** [comment]
mạng ở nhà không tốt, hóng tiếp rồi :(
