### ISSUE TITLE
Meetup ? - ??? - Cách tra cứu API

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/meetup#36]
Bạn có bao giờ tự hỏi cách để tìm tài liệu cho 1 API trong Ruby ra sao chưa?

Trong 5' bạn sẽ đc giới thiệu và giao ước cách gọi tên hàm trong Ruby (# cho instance method và :: hay . cho class/module method) và cách sử dụng `ri` hay tool khác như Dash (cho OSX) hay Website hoặc cách tự tạo ra Rails API doc riêng.

**Comment by thiensubs** [comment]
apipie-rails
http://blog.rubysg.com/2015/01/29/phong-cach-viet-api-document-chuyen-nghiep-cho-rails-voi-gem-apipie-rails/
Liệu bài viết này có dùng được ko bạn?

**Comment by hnq90** [comment]
@thiensubs Có vẻ như bạn hiểu sai ý rồi thì phải.

**Comment by joneslee85** [comment]
@thiensubs bạn hiểu sai ý của mình rồi, đề tài này là về phương pháp tra khảo documentation, đây là vấn đề nhiều bạn gặp khó khăn khi mới nhập môn

**Comment by thiensubs** [comment]
OK.
