### ISSUE TITLE
Meetup 6 - Chris Harvey - Job Finding Techniques

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/meetup#43]
Chris Harvey will give a talk on techniques that help you score a job in no time. Furthermore, writing a great CV is also covered.

**Comment by joneslee85** [comment]
:+1:

**Comment by huydx** [comment]
:+1:

**Comment by nnluukhtn** [comment]
:+1:

**Comment by qu4n** [comment]
(y)

**Comment by qu4n** [comment]
:+1:

**Comment by starchow** [comment]
:+1:

**Comment by stnguyen** [comment]
:+1: can I watch the talk on the internet?

**Comment by joneslee85** [comment]
@stnguyen sadly no, the Internet connection is horrible..
