### ISSUE TITLE
Meetup 6 - Use Capstriano to deploy anything

### ISSUE THREAD

**Issue by trankimhieu** [ruby-vietnam/meetup#44]
I want to talk about Capstriano because after use it to deploy my staging server. I feel very easy to use and it is a super good way to avoid touching server when deploy any app.

**Comment by MQuy** [comment]
IMO, I don't like Capstriano, it's quite slow. I think it should be better if you talk about general deployment process and compare between deployment tools :smile:

**Comment by trankimhieu** [comment]
@MQuy Ok, may be compare Cap with Shipit(Nodejs). In another side. I think it quite slow but reliable

**Comment by joneslee85** [comment]
@MQuy Haters gonna hate, sadly Cap is still a defacto method and I think it's worthy, I :+1:

**Comment by starchow** [comment]
I used Capistrano in the past, now I'm using mina for deployment. Mina is much faster and easier to use than Capistrano. It's like using heroku command line on your server.
But we should use the deployment tool instead of deploy a project step by step then again and again many times. So I :+1:

**Comment by hoang1417** [comment]
:+1: will be great if we have a comparison between them.

**Comment by joneslee85** [comment]
xong, khoá sổ :)
