### ISSUE TITLE
Meetup #? - An Nguyễn - Nhúng GridManager vào ActiveAdmin

### ISSUE THREAD

**Issue by crashbell** [ruby-vietnam/meetup#46]
Giới thiệu về `ActiveAdmin` gem và một chút về `GridManager` (https://github.com/neokoenig/jQuery-gridmanager). Cuối cùng là cách mình nhúng `GridManager` vào `ActiveAdmin`

**Comment by huydx** [comment]
@crashbell em định present ở phía hà nội hay HCM?

**Comment by crashbell** [comment]
em present ở HCM anh
