### ISSUE TITLE
Meetup 6 - Tu Hoang (@rebyn) - End-to-end testing for APIs & wrappers

### ISSUE THREAD

**Issue by rebyn** [ruby-vietnam/meetup#47]
- I'm splitting a monolithic app into single purpose services
- Wrappers are usually built along services as well for better adoption
- Test suites are maintained via both places (service & wrapper) and use mocks/stubs intensively
- Changes roll out frequently in services and wrappers' test suites aren't catching up (be it lack of priority or such effort intensive a task)
- There needs a tool to do end-to-end testing between the two: mocking services in wrappers and acting as a wrapper consuming services
- Let's talk about [pact](https://github.com/realestate-com-au/pact).

**Comment by joneslee85** [comment]
@rebyn hello there, is this for the saigon.rb or hanoi.rb?

**Comment by rebyn** [comment]
@joneslee85 hi anh, I'm in Saigon right now so it's gonna be for saigon.rb

**Comment by huydx** [comment]
:+1: seem very interesting
