### ISSUE TITLE
Meetup 6 - Nguyễn Đức Giang (@nguyenducgiang) - Fetch & Extract Content from Web Pages

### ISSUE THREAD

**Issue by nguyenducgiang** [ruby-vietnam/meetup#48]
Fetching web pages and extracting valuable content is a vital part of my project. I would like to share & discuss some of my experience related to this issue.

I will add more details here later.

**Comment by joneslee85** [comment]
:+1:

**Comment by huydx** [comment]
:+1:

**Comment by hungnv132** [comment]
yeah!

**Comment by stnguyen** [comment]
:+1:
