### ISSUE TITLE
Meetup 7 - Stefan Nguyen - Speed up game development with Ruby scripting language

### ISSUE THREAD

**Issue by stnguyen** [ruby-vietnam/meetup#49]
Ruby không chỉ để làm Web. Bản thân Ruby là một ngôn ngữ kịch bản rất đẹp, mạnh mẽ, có thể sử dụng để viết script tự động hóa, xử lý text files, viết standalone application chạy trên các nền tảng khác nhau như Windows, Mac, Linux...

Trong bài nói này, mình muốn chia sẻ kinh nghiệm thực tế sử dụng Ruby tạo các công cụ giúp cho phát triển game được nhanh hơn, dễ dàng hơn.

Qua các ví dụ thực tiễn, bài nói sẽ liên quan tới các kiến thức:

- Xử lý text với Regex.
- Gói ruby script thành standalone application bằng Rawr và JRuby để chạy độc lập trên Windows, Mac, Linux mà không cần máy đích cài Ruby.
- Tự động hóa quản lý game assets bằng cách nhúng Ruby script vào chạy trong XCode.

__Chú ý__:

- Bài nói mang tính chất demo ứng dụng của Ruby vào các lĩnh vực khác nhau hơn là chia sẻ kiến thức ngôn ngữ Ruby.
- Bài nói không nói về việc viết game bằng Ruby, mà là dùng Ruby tạo tools hỗ trợ các giai đoạn khác nhau của làm game.
- Bài nói mình ứng cử tham gia vào Meetup __lần tới tại Hà Nội__ (tháng 4/2015 ?), vì meetup tháng 3 sắp diễn ra mình không tham gia được.

**Comment by huynt57** [comment]
Các ngôn ngữ kịch bản thông dịch khi lập trình game có yếu thế hơn các ngôn ngữ biên dịch thông thường như C++, Java không ạ ?. Khả năng hỗ trợ đa nền tảng, tốc độ của ứng dụng và tính chặt chẽ khi thực thi giữa hai loại ngôn ngữ này nữa ạ. Em đang phân vân giữa hai vấn đề này, hy vọng a Tùng sẽ có đề cập thêm trong bài nói :+1:

**Comment by stnguyen** [comment]
@huynt57  bài này anh không nói về việc dùng ngôn ngữ Ruby để viết game. Bài nói này nói về dùng Ruby để tạo tools hỗ trợ các giai đoạn khác nhau của làm game.

**Comment by huynt57** [comment]
Thế ạ, thế lại hy vọng anh có bài nói nữa về vấn đề này :+1:

**Comment by nhattan** [comment]
:+1:  tuyệt vời anh @stnguyen

**Comment by huydx** [comment]
chủ đề này khá thú vị nên mình hoàn toàn :+1:

**Comment by joneslee85** [comment]
:+1:
