### ISSUE TITLE
Meetup 1/2016 - Nick Suterer (@apotonick) - Introduction to Trailblazer

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/meetup#50]
Rails frontend is very broken in its own right due to lack of a proper structure and convention. Users are left with many choices and mostly goes awry after the GUI gets more complex. Introducing Trailblazer, an additional layer to complement Rails stack that define a convention for View layer by introducing composition structure. 

Trailblazer is taking the world by storm with many companies are using it, would that be your company next?

**Comment by nnluukhtn** [comment]
:+1:

**Comment by nhattan** [comment]
:+1:  :+1:

**Comment by hoang1417** [comment]
:+1:

**Comment by quyetdc** [comment]
:+1:

**Comment by checkraiser** [comment]
:+1:

**Comment by hoang1417** [comment]
:+1:

**Comment by joneslee85** [comment]
kì này có vẻ căng vì mạng lởm, để mình hỏi xem anh Nick có quá cảnh ở VN không, nếu đc nói anh làm một bài

**Comment by nguyenducgiang** [comment]
:+1:

**Comment by huynhquancam** [comment]
:+1: hóng

**Comment by hiendinhngoc** [comment]
:+1:

**Comment by phongtattuan** [comment]
:+1: :+1:

**Comment by saiury92** [comment]
:+1:

**Comment by giangstrider** [comment]
:+1:

**Comment by trankimhieu** [comment]
:+1:

**Comment by hnq90** [comment]
:100: :+1:
