### ISSUE TITLE
Meetup #5 - @hieuk09 - Refactor big query using AREL

### ISSUE THREAD

**Issue by hieuk09** [ruby-vietnam/meetup#52]
Big query with multiple nested queries is very hard to maintain. We can take advantage of the power of Arel to convert long SQL query to simple, nice Ruby methods. Those methods will be much easier for testing and maintenance.

**Comment by joneslee85** [comment]
For 2moro?

**Comment by hieuk09** [comment]
Of course not :) It will be in the future meetup.

**Comment by huydx** [comment]
:+1:

**Comment by joneslee85** [comment]
:+1: for meetup 4, :-1: for meetup ??

**Comment by joneslee85** [comment]
:+1:

**Comment by hieuk09** [comment]
Slide: http://www.slideshare.net/HieuNguyenTrung/using-arel-to-refactor-big-queries
