### ISSUE TITLE
Meetup 7 - @mymai @DonDinhIT- Chia sẻ cá nhân về nghề lập trình

### ISSUE THREAD

**Issue by DonDinhIT** [ruby-vietnam/meetup#53]
Chia sẻ cá nhân tại sao lại chọn nghề lập trình, và cảm nhận khi tham gia hoạt động cộng đồng và làm việc với các dự án mã nguồn mở.

**Comment by hoang1417** [comment]
go ahead, girls :+1:

**Comment by crashbell** [comment]
:+1:  

Don't know why no one voted her...

**Comment by huydx** [comment]
:+1:

**Comment by joneslee85** [comment]
:100:
