### ISSUE TITLE
Meetup 7 - @vinhngl- Problem with nil and how to avoid them

### ISSUE THREAD

**Issue by vinhngl** [ruby-vietnam/meetup#54]
Sometime in the Rails app, you will see the error `NoMethodError: undefined method '...' for nil:NilClass `. So how did you solve it? I'll introduce 3 common ways to solve this problem.

**Comment by joneslee85** [comment]
Sound like a nice talk, 5' ?

**Comment by vinhngl** [comment]
Yes. Just 5 mins

On Wednesday, May 13, 2015, Trung Lê <notifications@github.com> wrote:

> Sound like a nice talk, 5' ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruby-vietnam/meetup/issues/54#issuecomment-101509466>.
>


-- 
Web Developer
AsNet Informatics & Trading Co., Ltd
604 Nui Thanh street, Hai Chau district, Da Nang city, Viet Nam
Phone: (+84) 1206147995
Skype: vinhnguyenle.asnet
Email: vinh.nguyenlexuan@asnet.com.vn

**Comment by hoang1417** [comment]
:+1:

**Comment by hienvd** [comment]
:+1:

**Comment by crashbell** [comment]
(y)

**Comment by crashbell** [comment]
:+1:

**Comment by vinhngl** [comment]
Slide for meetup: [Problem with nil and How to avoid them](https://docs.google.com/presentation/d/1HMVzCHnRVy7oZxBAobNIHhjFzFwyu3GBLp4rg0bnPjo/edit?usp=sharing)
