### ISSUE TITLE
Meetup 4 - Nguyễn Thị Ngọc, Phạm Thị Thùy (@nguyenngoc2505, @thuypt)- Khi những cô gái trở thành lập trình viên

### ISSUE THREAD

**Issue by nguyenngoc2505** [ruby-vietnam/meetup#55]
- Chia sẽ những kinh nghiệm, tại sao chọn nghề, và những cảm nhận khi tham gia vào những dự án mã nguồn mở

**Comment by joneslee85** [comment]
@nguyenngoc2505 em muốn làm cho saigonrb hay hanoirb?

**Comment by nguyenngoc2505** [comment]
@joneslee85 : bọn em đang ở hà nội nên bài này bọn em sẽ làm luôn cho hanoirb ạ.
