### ISSUE TITLE
Meetup 7 - @MadRabbit Tạo trò chơi Street Fighter II với Ruby

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/meetup#56]
![](http://www.fightersgeneration.com/np5/gm/sf2-s3.jpg)

Ai cũng chắc đã chơi qua trò Street Fighter của hãng Capcom. Anh Nemshilov, một kỹ sư phần mềm có tiếng đến từ cty Ninefold sẽ trình bày cách viết game trên với gosu. Bài nói sẽ được trình bày bằng tiếng Anh và qua mạng, nếu mọi ng thích thì xin hãy cho 1 tràng :+1: ở dưới

**Comment by phiendp** [comment]
:+1:

**Comment by nhattan** [comment]
:+1:  /play yeah

**Comment by nguyenngoc2505** [comment]
:+1:

**Comment by huytd** [comment]
:+1:

**Comment by mymai91** [comment]
(y)

**Comment by jonathan-vinova** [comment]
:+1:

**Comment by joneslee85** [comment]
:100:

**Comment by hoang1417** [comment]
:+1:

**Comment by GinVlad** [comment]
:+1:

**Comment by khandz** [comment]
:+1:

**Comment by catvm** [comment]
+1

**Comment by hienvd** [comment]
:+1:
