### ISSUE TITLE
Meetup 7 - @vumanhcuongit - Form Objects in Rails

### ISSUE THREAD

**Issue by vumanhcuongit** [ruby-vietnam/meetup#57]
I intend to talk about *Form Objects in Rails*. The presentation will focus three main points:
 * What is form objects?
 * Why is it worth using?
 * How to implement it?

**Comment by vumanhcuongit** [comment]
Tại sao các bạn nên vote up:
 * Tui mô tả issue bằng tiếng Anh thôi chứ nói bằng tiếng Việt :trollface: 
 * Meetup 7 lần này có giới hạn chỗ ngồi, phải đăng ký sớm mới được, nên tui phải đi đường vòng để được tham dự meetup lần này :(

**Comment by phiendp** [comment]
:+1:

**Comment by joneslee85** [comment]
lol, :+1: for the pitch

**Comment by hoang1417** [comment]
lol, :+1:

**Comment by rebyn** [comment]
lol :100:

**Comment by joneslee85** [comment]
@vumanhcuongit vì đã có nhiều bài lần trước nói về form object, em có thể rút xuống thành bài 5' đc không? và dành thời gian 10' để tra đổi thêm với mọi người

**Comment by vumanhcuongit** [comment]
@joneslee85 OK anh, như vậy trong bài 5' em sẽ trình bày "Tại sao nên dùng Form Objects?".

**Comment by vumanhcuongit** [comment]
Mình gửi mọi người link slide: goo.gl/Auxmr0
