### ISSUE TITLE
Meetup 7 - @vinh0604 - Các lỗi bảo mật thường gặp của Rails

### ISSUE THREAD

**Issue by vinh0604** [ruby-vietnam/meetup#58]
I would like to share some common but very critical security mistakes that every web developer could easily fall into and some ways to deal with them in Rails:
- XSS
- SQL Injection
- Insecure cookies

**Comment by voanhduy1512** [comment]
:+1:

**Comment by viphat** [comment]
:+1:

**Comment by tma-dathi** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by PhamBaTho** [comment]
:+1:

**Comment by phiendp** [comment]
:+1:

**Comment by lethanhquang** [comment]
:+1:

**Comment by thanhtung2806** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by hoang1417** [comment]
:+1:

**Comment by vumanhcuongit** [comment]
+1

**Comment by minhdanh** [comment]
:+1:

**Comment by huydx** [comment]
:+1:

**Comment by duythanh** [comment]
bem bem, vote cho a để có cơ hội nói ạ, chứ e hiện tại chưa đủ trình để quan tâm, sau này hy vọng có :P blè blè

**Comment by hoangviet** [comment]
:+1:

**Comment by hienvd** [comment]
:+1:

**Comment by dattengichaduoc** [comment]
:+1:
