### ISSUE TITLE
Meetup 8 - @checkraiser - Writing Rails FrontEnd using React.js stack

### ISSUE THREAD

**Issue by checkraiser** [ruby-vietnam/meetup#59]
We should rewite the default frontend Rails with this frontend stack:
- Webpack for bundling Javascript
- React.JS for Javascript View
- BaconJS for Reactive update

Rails provides only API for the frontend to serve.

Benefit of this architecture: 
- We seperate completely the frontend and backend code !
- We could use modern Node.js toolbelts to focus on Frontend
- We could focus on API on Rails only (no need for messy views any more)
...

**Comment by vinhngl** [comment]
:+1:

**Comment by hoang1417** [comment]
:+1:

**Comment by joneslee85** [comment]
:+1:

**Comment by quyetdc** [comment]
:+1:

**Comment by huynhquancam** [comment]
:+1:

**Comment by demonkid98** [comment]
:+1:

**Comment by hiendinhngoc** [comment]
:+1:

**Comment by voanhduy1512** [comment]
:+1:

**Comment by duytd** [comment]
:+1:

**Comment by vumanhcuongit** [comment]
:100:

**Comment by crashbell** [comment]
:+1:

**Comment by baothi** [comment]
:+1:
