### ISSUE TITLE
Meetup 8 - @huynhquancam - Rails client-side validation with bootstrap_validator_rails

### ISSUE THREAD

**Issue by huynhquancam** [ruby-vietnam/meetup#60]
Writing client-side validations in JS is so tiring, what would it be like if the validation scripts were automatically generated using your model validations?

I'd like to introduce my personal open-source project `bootstrap_validators_rails` (https://github.com/huynhquancam/bootstrap_validator_rails) on how this gem might solve the client-side validation problem.

Agenda:

* Fast introduction of the gem.
* Demo.
* Q&A.

**Comment by joneslee85** [comment]
Như vậy validation này là có cả trên server và client side hay chỉ có client?

**Comment by huynhquancam** [comment]
Nó sẽ đọc validation trong models và tự sinh ra mã javascript hoặc html5 data attributes tương ứng (https://github.com/formvalidation/formvalidation) để validate client-side, còn trên server thì nó vẫn validate như bình thường thôi anh. :smiley:

**Comment by vumanhcuongit** [comment]
:+1:

**Comment by phiendp** [comment]
:+1:

**Comment by joneslee85** [comment]
:+1: (vậy thì dùng nodejs đi nhỉ :trollface:)

**Comment by huynhquancam** [comment]
e lỡ viết Ruby rồi :hushed: ... hay là giờ dùng Opal cho đỡ viết lại anh nhỉ :laughing:

**Comment by mymai91** [comment]
:+1:

**Comment by joneslee85** [comment]
@huynhquancam bị dội lại quả Opal, vãi troll

**Comment by stevenyap** [comment]
Up

**Comment by duykhoa** [comment]
@huynhquancam  nghe lời bác winston ghê ta ui! Like it :heart_decoration:

**Comment by voanhduy1512** [comment]
:+1:

**Comment by hiendinhngoc** [comment]
:+1:

**Comment by baothi** [comment]
:+1:
