### ISSUE TITLE
Meetup 8 - @trankimhieu (Hieu Tran) - Viết nhanh một API để sử dụng với Slack command

### ISSUE THREAD

**Issue by trankimhieu** [ruby-vietnam/meetup#61]
Hi `all`,

When we use `Slack` at our office. We want to integrate all in one collaboration working space and we use Slack to give the reward to teammate and use Slack to order food.
So now, we want to share to you how to use `Ruby + Lotus` and `NodeJS + Express` (two languages) to write a small application to execute Slack command.

Time: 15 minutes
Tools: Text editor, Ruby/Node, Slack, Heroku
Objectives: Code for fun, extend Slack

**Comment by trankimhieu** [comment]
@joneslee85 Help me review, check spell and add tags please

**Comment by joneslee85** [comment]
@trankimhieu good luck, I hope you are able to squeeze in 2 languages in 1 session.

Can I order a :hamburger: now? :+1:

**Comment by trankimhieu** [comment]
@joneslee85 I think I will code already and tagged on git. So go through step by step and show how. Not need to code.

**Comment by huydx** [comment]
:+1:

**Comment by huytd** [comment]
:+1:

**Comment by bdthinh** [comment]
:+1: exciting

**Comment by cuong-nguyen-ta** [comment]
(y)

**Comment by baothi** [comment]
:+1:

**Comment by hdanh** [comment]
👍

**Comment by batlongthien** [comment]
(y)

**Comment by phiendp** [comment]
:+1:

**Comment by mymai91** [comment]
:+1:

**Comment by HuuThuan0701** [comment]
:+1:

**Comment by nguyenquangminh0711** [comment]
:+1:

**Comment by linhpham** [comment]
:+1:

**Comment by qu4n** [comment]
(y)

**Comment by thaod** [comment]
:+1:

**Comment by luuhai** [comment]
(Y)

**Comment by sondinh2702** [comment]
:+1

**Comment by nktanh** [comment]
:+1:

**Comment by thanhtranvan** [comment]
:100: :+1:

**Comment by huuthonguyen76** [comment]
:+1:

**Comment by vanlan228** [comment]
:+1:

**Comment by joneslee85** [comment]
Quá dữ, bà con đông đảo ủng hộ, good luck @trankimhieu

**Comment by nhattan** [comment]
(Y)

**Comment by huytd** [comment]
Nhớ share slide nhé bác @trankimhieu 
Mình ở ĐN ko tham gia meetup đc :(
