### ISSUE TITLE
Meetup #8 - anvotien - Giới thiệu cách tích hợp một số BackgroudWorker với ActiveJob - Rails 4.2

### ISSUE THREAD

**Issue by thiensubs** [ruby-vietnam/meetup#62]
Hi all,
Hướng tiếp cận:
- Dễ thấy: Cụ thể và dễ dàng nhìn nhận với các Rails dev đó là việc khi ứng dụng gởi email, nếu như bình thường thì khi ứng dụng chạy qua dòng lệnh gởi email, ứng dụng sẽ chờ đến khi email được gởi xong mới thực hiện dòng lệnh phía dưới. Điều này sẽ làm ứng dụng chậm đi, chưa kể đến việc khá nguy hiểm khi chúng ta vô tình check điều kiện email có được gởi hay không để thực hiện một kết quả có giá trị nào đó.
- Lớn hơn: Tăng hiệu suất xử lý các công việc, giúp app Rails chạy trơn tru hơn. (Indexing Data, Ranking, etc...)

Qua bài viết mình sẽ trình bày cách cài đặt đơn giản với một số BackgroudWoker phổ biển như Sidekiq, DJ, SuckerPunch, Sneaker, etc... với ActiveJob trên Rails 4.2

Time: 5/ 15 minutes.
Tools: Sublimext, POSTMAN, and Example in my Rails app.

**Comment by hieuk09** [comment]
:+1:

**Comment by hieuk09** [comment]
Cái này ở SG hay HN vậy bạn?

**Comment by thiensubs** [comment]
Dạ, SG anh.

**Comment by joneslee85** [comment]
Nếu bài này 5' thì có thể xem xét đưa vào vì hiện đã có 3 bài 15' khác, khá là đầy.

**Comment by huydx** [comment]
:+1:

**Comment by phongtattuan** [comment]
:+1:

**Comment by hoang1417** [comment]
:+1:

**Comment by hoanghiep90** [comment]
(y)

**Comment by thanhcuong1990** [comment]
:+1:

**Comment by joneslee85** [comment]
:+1:

**Comment by hoangvukenshin** [comment]
:+1:

**Comment by nusdavid** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by joneslee85** [comment]
accepted, good luck
