### ISSUE TITLE
Meetup #5 - @huydx - NoSQL database for great good

### ISSUE THREAD

**Issue by huydx** [ruby-vietnam/meetup#63]
Nói về đặc trưng của một số NoSQL tiêu biểu
Điểm yếu điểm mạnh của từng loại
Cách chọn NoSQL database cho dự án

**Comment by joneslee85** [comment]
:+1:

**Comment by nguyenducgiang** [comment]
:+1:

**Comment by xluffy** [comment]
(y)

**Comment by phongtattuan** [comment]
:+1:

**Comment by nhattan** [comment]
:+1:

**Comment by hieuk09** [comment]
Slides: http://www.slideshare.net/dxhuy88/nosql-for-great-good-hanoirb-talk
