### ISSUE TITLE
Meetup 5 - Imamura - power_assert with RSpec

### ISSUE THREAD

**Issue by pacuum** [ruby-vietnam/meetup#64]
power_assert provides descriptive assertion messages through standard assert interface.
It is a small but useful gem to make your test/spec readable for developers and make the error message far more meaningful.
https://github.com/joker1007/rspec-power_assert

* Problems of rspec matchers
* What is Power Assert
* How to use Power Assert with RSpec

**Comment by nhattan** [comment]
:+1:

**Comment by nguyenducgiang** [comment]
:+1:

**Comment by mymai91** [comment]
:+1:

**Comment by huynhquancam** [comment]
:+1:

**Comment by huydx** [comment]
:+1+

**Comment by joneslee85** [comment]
:+1:

**Comment by luuhai** [comment]
:+1:

**Comment by giangnguyennet** [comment]
:+1:

**Comment by hieuk09** [comment]
Hi @pacuum, could you please upload your slide?
