### ISSUE TITLE
Meetup tháng 10 - My - SMS Verify tài khoản đăng nhập bằng số điện thoại (Rails + Gem Twilio)

### ISSUE THREAD

**Issue by mymai91** [ruby-vietnam/meetup#67]
Currently, Having more app use phone_number to create accout like Viber, zalo...
This is the step how it work:

Step 1: Input phone number
Step 2: Submit phone number
Step 3: Generater a pin code
Step 4: Send pin code to user by SMS
Step 5: User got a pin code and input it into field pin code to verify
To apply step 4 having gems support it like Twilio or Nexmo...
In this topic I will introduce the way apply gem Twilio

Slide: https://docs.google.com/presentation/d/1vTw9DTWJ-4iA4QGObYmS3xPr_knONzjSAu7wVMZMp5E/edit?usp=sharing

**Comment by joneslee85** [comment]
Please update description

**Comment by mymai91** [comment]
Currently, Having more app use phone_number to create accout like Viber, zalo...
This is the step how it work:
* Step 1: Input phone number
* Step 2: Submit phone number
* Step 3: Generater a `pin code`
* Step 4: Send `pin code` to user by SMS
* Step 5: User got a `pin code` and input it into field `pin code` to verify

To apply **step 4** having gems support it like Twilio or Nexmo...
In this topic I will use Twilio

**Comment by joneslee85** [comment]
@mymai91 please edit and update the issue description

**Comment by mymai91** [comment]
@joneslee85 I have described above. Is it not correct?

**Comment by joneslee85** [comment]
@mymai91 you are supposed to describe the problems. What is it here? Too many steps, prone for error? Not intuitive for UX?

**Comment by mymai91** [comment]
@joneslee85 I update it. Is it correct?

**Comment by joneslee85** [comment]
:+1:

**Comment by mymai91** [comment]
@joneslee85 Can you help me review slide?

**Comment by joneslee85** [comment]
@mymai91 surely, please grant me edit rights

**Comment by mymai91** [comment]
@joneslee85 Added. Please help
