### ISSUE TITLE
Meetup tháng ?? - Tuấn Anh - Growing Rails

### ISSUE THREAD

**Issue by rockkhuya** [ruby-vietnam/meetup#68]
Bài nói 15p về cấu trúc và cách bố trí controller trong trường hợp project lớn.

**Comment by joneslee85** [comment]
@rockkhuya bạn nộp cho meetup saigon.rb hay dannang.rb?

**Comment by rockkhuya** [comment]
@joneslee85 Mình nộp cho meetup danang.rb :)

**Comment by joneslee85** [comment]
:+1:

**Comment by joneslee85** [comment]
cc @mymai91

**Comment by mymai91** [comment]
@joneslee85 Got it.

**Comment by joneslee85** [comment]
@mymai91 please post on FB for ppl to come voting

**Comment by huytd** [comment]
:+1:

**Comment by mymai91** [comment]
@rockkhuya Can you push out your slide?

**Comment by vinhnglx** [comment]
@mymai91 @joneslee85 He will talk in the next meetup.

**Comment by joneslee85** [comment]
@vinhnglx I've just unassigned him from this Oct Meetup milestone

btw, great job last nite
