### ISSUE TITLE
Meetup tháng 10 - Cao Quảng Bình - ActiveRecord Association & Database (MySQL)

### ISSUE THREAD

**Issue by CQBinh** [ruby-vietnam/meetup#69]
Bài nói 5 phút về vấn đề toàn vẹn dữ liệu trong rails, những quan niệm sai lầm về quan hệ giữa các `model` và giải pháp khắc phục.
Slide: https://www.dropbox.com/s/t2schwf5pl3kido/AsianTech_ActiveRecord%20Asscociation%20and%20MySQL.odp?dl=0 (updated 23/10 16:30)

**Comment by joneslee85** [comment]
:+1:

**Comment by joneslee85** [comment]
Thanks @CQBinh for the great talk, looking forward to seeing more sharing from you in the future.

Though not being there, I overheard the conversation, and it seems to me that this topic could become a main topic of a hacknight
