### ISSUE TITLE
Meetup tháng 11 - @hoasung01 - Delegate

### ISSUE THREAD

**Issue by hoasung01** [ruby-vietnam/meetup#70]
Hướng dẫn sử dụng delegate thông qua một demo đơn giản trong 5 phút :) 

Slide có thể tìm thấy tại   <a href="https://speakerdeck.com/hoasung01/ruby-meetup-delegate">link</a>

**Comment by phongtattuan** [comment]
:+1:

**Comment by joneslee85** [comment]
:+1:

**Comment by quocnv** [comment]
@hoasung01  còn gì khác không, PA hết coi :D

**Comment by rhacker** [comment]
example code đi anh, mới ý kiến tiếp được :D

**Comment by joneslee85** [comment]
@hoasung01 góp ý là nên cắt nghĩa delegation pattern cho đám đông rồi mới nhảy vào giới thiệu cách làm của Ruby, nếu mà có thể giới thiệu đc luôn cách Rails làm thì càng tốt.

**Comment by hoasung01** [comment]
delegate(*methods) Link
    Provides a delegate class method to easily expose contained objects' public methods as your own.

    Options

    :to - Specifies the target object
 
    :prefix - Prefixes the new method with the target name or a custom prefix

    :allow_nil - if set to true, prevents a NoMethodError to be raised
 
    The macro receives one or more method names (specified as symbols or strings) and the name of the   target object via the :to option (also a symbol or string).

    Delegation is particularly useful with Active Record associations:

Trong bài present 5' của mình, mình sẽ hướng dẫn cách sử dụng cái hàm delegate này khi ứng dụng trong một project. Với trường hợp có sử dụng delegate và trường hợp không sử dụng delegate khi truy xuất thuộc tính của các tables có quan hệ với nhau.

**Comment by hoasung01** [comment]
@quocnv: được chưa
@rhacker: example code là API ở trên thôi :)
@joneslee85: dạ, anh. Sẽ có cắt nghĩa cho delegate trước khi vào demo. Còn cách làm của Rails thì em nghĩ show cái hàm delegate trong API là đủ rồi nhỉ?

**Comment by rebyn** [comment]
:+1: 5m talk FTW

**Comment by joneslee85** [comment]
@hoasung01 uhm

**Comment by taminhtien** [comment]
+1
