### ISSUE TITLE
Meetup tháng 11 - huynhquancam - Monkey Patching an toàn với Ruby

### ISSUE THREAD

**Issue by huynhquancam** [ruby-vietnam/meetup#71]
Meetup 11/2015 - Cẩm (@huynhquancam) - Monkey-Patching an toàn trong Ruby

> Đã bao giờ bạn vò đầu bứt tai vì không hiểu hàm `Array#to_query` ở đâu ra, sau khi đã đọc kỹ Ruby-Doc mà vẫn không thấy?

Bài nói của mình sẽ về Monkey patching, một kỹ thuật vừa-nguy-hiểm-vừa-hữu-dụng trong lập trình Ruby, chủ yếu bao gồm 3 phần:

- Monkey patching là gì?
- Một số cách để monkey-patch một cách có "code đức".
- Phát biểu cảm nghĩ cá nhân về monkey patching.

Slide có thể tìm thấy tại [link](https://speakerdeck.com/hqc/monkey-patching-in-ruby)

**Comment by hoang1417** [comment]
:+1:

**Comment by joneslee85** [comment]
:+1:

**Comment by hiendinhngoc** [comment]
+1

**Comment by phongtattuan** [comment]
:+1:

**Comment by qu4n** [comment]
:+1:

**Comment by vumanhcuongit** [comment]
:100:

**Comment by huydx** [comment]
:+1: cho quần cam

**Comment by ntamvl** [comment]
:+1:

**Comment by dnson** [comment]
:+1

**Comment by vinhnglx** [comment]
:+1:

**Comment by gagoit** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by taminhtien** [comment]
:+1:

**Comment by conficker1805** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by duykhoa** [comment]
[:+1:](http://lgtm.in/u/eLIxbB11q) [:-1:](http://lgtm.in/r/eLIxbB11q)
