### ISSUE TITLE
Meetup tháng 11 - vinhnglx - Saddler check style code

### ISSUE THREAD

**Issue by vinhnglx** [ruby-vietnam/meetup#72]
Bài nói giới thiệu về cách setup [Saddler](http://packsaddle.org/) với Circle CI để kiểm tra code style. 

- Trước đây mình đã từng dùng [HoundCI](https://houndci.com/) cho việc check code style. Tuy nhiên với private repo chúng ta phải trả 12$/month cho HoundCI.
- Gần đây mình tìm hiểu được có thể dùng [Saddler](http://packsaddle.org/). Kết hợp cùng với Circle CI để check code. 

Cho nên trong bài nói 5p này, mình sẽ giới thiệu về Saddler và cách integrate với Circle để check code style cho mỗi PR 

Slide: [https://speakerdeck.com/vinhngl/saddler-hcmc-meetup-2015](https://speakerdeck.com/vinhngl/saddler-hcmc-meetup-2015)

**Comment by joneslee85** [comment]
:+1:

**Comment by huytd** [comment]
:+1:

**Comment by huynhquancam** [comment]
:+1:

**Comment by hoangtran-asnet** [comment]
+1

**Comment by nhattan** [comment]
:+1:

**Comment by duykhoa** [comment]
:100: :+1:

**Comment by mymai91** [comment]
:+1:

**Comment by phongtattuan** [comment]
:+1:

**Comment by hoang1417** [comment]
:+1:

**Comment by vinhnglx** [comment]
Slide: https://speakerdeck.com/vinhngl/saddler-hcmc-meetup-2015

**Comment by joneslee85** [comment]
@vinhnglx :100:

**Comment by nongdenchet** [comment]
:+1:
