### ISSUE TITLE
Meetup tháng 12 - Khoa Tran - Polymer in a Rails Dev perspective.

### ISSUE THREAD

**Issue by duykhoa** [ruby-vietnam/meetup#73]
Mình muốn chia sẻ về cảm nhận sau khi dùng polymer js cho dự án Rails.

Trong bài sẽ có 4 phần: 

- Tại sao mình chọn polymer.
- Mình xài thế nào
- Một cái Demo nhỏ
- 1 số resources cho các bạn quan tâm.

**Comment by huynhquancam** [comment]
:+1:

**Comment by vinhnglx** [comment]
:+1:

**Comment by joneslee85** [comment]
:+1:

**Comment by joneslee85** [comment]
@duykhoa can you please provide more details on this talk?

**Comment by duykhoa** [comment]
@joneslee85 Thanks for asking, give me sometimes to figure out. Will update soon :smiley:

**Comment by hoang1417** [comment]
@duykhoa, you will travel to Da Nang at the meetup time or you're living there? :joy: Wanna see you talk in HCM though.

**Comment by duykhoa** [comment]
Nope, via google hangout @hoang1417.

**Comment by anduonghien** [comment]
:+1:

**Comment by mymai91** [comment]
@duykhoa lam chuyen da nang di ban hien

**Comment by trivv** [comment]
(Y)

**Comment by vinhnglx** [comment]
slide: https://docs.google.com/presentation/d/1jmiuFen89OtNW53loa6pXXKNWs78VF2qrFzDqeTkw5I/edit#slide=id.gf341f4445_0_3856
