### ISSUE TITLE
Meetup 1/2016 - Piotr Solnica (@solnica) - Intro to ROM (Ruby Objet Mapper) 

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/meetup#74]
Piotr Solnica is a well-known Rubyist hacker, having been involved in may famous projects like Virtus, ROM, Rodokase, ROM, etc. He has been experimenting with many ORMS and come into conclusion that ORM is not the way, thus alone pushed himself onto a new project, ROM (Ruby Object Mapper). If you would like to know why ROM is better in concept than ORMs. Vote for him

Screencast https://www.youtube.com/watch?v=hd3ZRnY1SOk

**Comment by huynhquancam** [comment]
:+1:

**Comment by hoang1417** [comment]
:+1:

**Comment by giangstrider** [comment]
:+1:

**Comment by joneslee85** [comment]
:+1:

**Comment by duykhoa** [comment]
:+1:

**Comment by vinhnglx** [comment]
+1

On Tue, Dec 8, 2015 at 10:17 AM, Tran Duy Khoa <notifications@github.com>
wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruby-vietnam/meetup/issues/74#issuecomment-162746929>.
>



-- 
Ruby/Rails Developer
AsianTech inc
Floor 6, VTN3 building, Street No 3, An Don Industrial Zone, Da Nang city
Phone: (+84) 1206147995
Skype: vinhnglx
Email: vinh.nglx@gmail.com

**Comment by hiendinhngoc** [comment]
:+1:

**Comment by phongtattuan** [comment]
:+1:

**Comment by hoangtran-asnet** [comment]
:+1:

**Comment by mmeeoorroo** [comment]
:+1:

**Comment by anhtai87** [comment]
+1

**Comment by phongtattuan** [comment]
:+1:

**Comment by viphat** [comment]
:+1:

**Comment by nnluukhtn** [comment]
:+1:
