### ISSUE TITLE
Meetup tháng 12 - Vu Nhat Minh (@DTVD) - Domain-Driven Design for Microservices Architecture

### ISSUE THREAD

**Issue by vinhnglx** [ruby-vietnam/meetup#75]
* Những tư tưởng cơ bản của Domain-Driven Design (DDD)
* Phương pháp dùng DDD cùng với kiến trúc Microservices khi xây dựng hệ thống lớn.
+ α: Software Engineer life in Japan.

**Comment by joneslee85** [comment]
Interesting, are you sure this is Ruby-related? Looks to me more like MongoDB + NodeJS lol

**Comment by DTVD** [comment]
Nhờ bạn @vinhnglx update lại title hộ mình:

* Title: Domain-Driven Design for Microservices Architecture
* Mình sẽ chia sẻ 3 phần
  * Những tư tưởng cơ bản của Domain-Driven Design (DDD)
  * Phương pháp dùng DDD cùng với kiến trúc Microservices khi xây dựng hệ thống lớn.
  * + α: Software Engineer life in Japan.

@joneslee85 lần này em chia sẻ chủ yếu về DDD thôi ạ.

**Comment by phongtattuan** [comment]
:+1:

**Comment by vinhnglx** [comment]
:+1:

**Comment by joneslee85** [comment]
:+1:

**Comment by thomastran** [comment]
:+1:

**Comment by xluffy** [comment]
:+1:

**Comment by mymai91** [comment]
:+1:

**Comment by longkt90** [comment]
:+1:

**Comment by vinhnglx** [comment]
slide show: http://slides.com/minhnhat/dddformicroservices#/
