### ISSUE TITLE
Meetup 1/2016 - @checkraiser - Xây dựng kiến trúc Microservice với Rabbitmq

### ISSUE THREAD

**Issue by checkraiser** [ruby-vietnam/meetup#77]
- Mô phỏng 1 case study cho kiến trúc Microservice dùng RabbitMQ
- Ưu điểm / Nhược điểm của kiến trúc này

Các bạn có thể xem slide ở  [đây](https://yg77eet5ead0y8ka0jso.oasis.sandstorm.io/index.html#/).

Nếu có mọi câu hỏi, mình sẽ trả lời, và cập nhật vào slide luôn. 

Question @[Slack RubyVN](https://vietnamrb.slack.com)

Demo:

Write server: [https://hpu-cas.herokuapp.com/tasks](https://hpu-cas.herokuapp.com/tasks)

Read server: [https://hpu-dashboard.herokuapp.com](https://hpu-dashboard.herokuapp.com)

Test:

- Thao tác trên Write server sẽ update realtime trên read server.
- Thao tác trên trực tiếp `pgadmin` sẽ update realtime trên cả 2 server

**Comment by joneslee85** [comment]
+1

**Comment by giangstrider** [comment]
:+1:

**Comment by quannt** [comment]
:+1:

**Comment by phongtattuan** [comment]
:+1:

**Comment by xluffy** [comment]
:+1:

**Comment by vinhnglx** [comment]
:+1:

**Comment by saiury92** [comment]
:+1:

**Comment by nnluukhtn** [comment]
:+1:

**Comment by huynhquancam** [comment]
`10.times {` :+1: `}`

**Comment by trankimhieu** [comment]
+1

**Comment by hnq90** [comment]
:100: :+1:

**Comment by vuthaihoc** [comment]
:+1:

**Comment by mmeeoorroo** [comment]
:+1:

**Comment by minhdanh** [comment]
:+1:

**Comment by dat-vinvoice** [comment]
Like

**Comment by checkraiser** [comment]
Mình đã cập nhật đường dẫn cho `slide` và `demo` .

**Comment by nguyenducgiang** [comment]
:+1:

**Comment by hoang1417** [comment]
:+1:

**Comment by mymai91** [comment]
:+1:

**Comment by tunglam14** [comment]
:+1:
