### ISSUE TITLE
Meetup 1/2016 - Huy Đỗ (@huydx) - Giới thiệu Dependency Injection trong Ruby

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/meetup#78]
Dependency Injection hay tắt là DI là một design pattern không có gì là mới mẻ. Hiểu và áp dụng đc pattern này thực sự sẽ mang lại nhiều lợi thế cho phần mềm của bạn. Nếu bạn còn mù mờ và thắc mắc thì hãy bình chọn cho bài nói này

http://www.slideshare.net/dxhuy88/di-in-ruby

**Comment by phongtattuan** [comment]
:+1:

**Comment by viphat** [comment]
:+1:

**Comment by vinhnglx** [comment]
:+1:

**Comment by nnluukhtn** [comment]
:+1:

**Comment by huynhquancam** [comment]
:+1:

**Comment by hiendinhngoc** [comment]
:+1:

**Comment by vumanhcuongit** [comment]
:100:

**Comment by anhtai87** [comment]
<img class="emoji" title=":+1:" alt=":+1:" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png" height="20" width="20" align="absmiddle">

**Comment by tiev** [comment]
:+1:

**Comment by saiury92** [comment]
:+1:

**Comment by giangstrider** [comment]
:+1:

**Comment by longkt90** [comment]
:+1:

**Comment by mmeeoorroo** [comment]
:+1:

**Comment by leo009394** [comment]
(Y)

**Comment by dieuit07** [comment]
:+1:

**Comment by buithehien1991** [comment]
:+1:
Ở SG hả anh?

**Comment by minhdanh** [comment]
:+1:

**Comment by nhattan** [comment]
:+1:

**Comment by nvh0412** [comment]
:+1:

**Comment by hoang1417** [comment]
:100:

**Comment by dathi** [comment]
:+1:
