### ISSUE TITLE
Meetup ?/2016 - José Valim - Elixir for Rubyist (intro) 

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/meetup#79]
Ngôn ngữ Elixir là một ngôn ngữ lập trình hướng chức năng mới, ra đời vào 2011 với nền tảng dựa trên Erlang VM. Đã không ít nhiều các cty trên thế giới chuyển qua sử dụng Elixir thay vì Ruby cho các ứng dụng đòi hỏi concurrency cao và gặt hái đc nhiều thành công nhất định. Nếu tính về độ tuổi của ngôn ngữ này thì thực sự đó là một thành công đáng đc sự quan tâm của mọi người. Thế Elixir là gì? Functional Programming là gì? Nó có phù hợp với bạn? Hãy để dành tất cả các câu hỏi cho anh vào ngày meetup. 

Nếu bạn muốn biết về Elixir từ chính tác giả của ngôn ngữ hay bầu chọn ngay bây giờ

**Comment by phongtattuan** [comment]
:+1:

**Comment by vumanhcuongit** [comment]
:100:

**Comment by huynhquancam** [comment]
:+1:

**Comment by thomastran** [comment]
:+1:

**Comment by giangstrider** [comment]
:+1:

**Comment by huydx** [comment]
:+1:

**Comment by unrealhoang** [comment]
:+1:

**Comment by rebyn** [comment]
:+1:

**Comment by longkt90** [comment]
:+1:

**Comment by saiury92** [comment]
:+1:

**Comment by hoang1417** [comment]
:+1:

**Comment by kiennt** [comment]
(y)

**Comment by hoang1417** [comment]
:+1:

**Comment by rebyn** [comment]
Cool bean.

**Comment by runlevel5** [comment]
Tình hình là ảnh bận, chắc phải tháng 5 mới đc :(

**Comment by nickqueen1989** [comment]
:+1:
