### ISSUE TITLE
Meetup 1/2016 - Bùi Thế Hiển (@buithehien1991) - Tổng quan về Background Worker và demo

### ISSUE THREAD

**Issue by buithehien1991** [ruby-vietnam/meetup#80]
Mình thấy bài nói về background jobs trong HCM có vài bài rồi nhưng HN thì chưa, vậy nên mình mạn phép xin nói về vấn đề này.
Nội dung bài nói dự kiến:
- Giới thiệu ưu/nhược điểm của các Background Worker
- Live demo về sử dụng Sidekiq hoặc một số Background Worker nổi bật

Đối tượng hướng tới: Người mới bắt đầu hoặc chưa sử dụng Background Worker
Độ dài: 15 phút.
Địa điểm: Hà Nội

**Comment by trankimhieu** [comment]
:+1:

**Comment by phongtattuan** [comment]
:+1:

**Comment by joneslee85** [comment]
:+1:

**Comment by giangstrider** [comment]
:+1:

**Comment by revskill10** [comment]
:+1:
