### ISSUE TITLE
Meetup ? - ??? - Deploy rails app for newbie

### ISSUE THREAD

**Issue by buithehien1991** [ruby-vietnam/meetup#81]
Chào mọi người.
Mình là người mới code Plugin Redmine được hơn 1 năm, nhưng khi bắt đầu xây dựng áp của riêng  thì gặp các vấn đề sau: 
- Deploy trên server nào (Passenger, Unicorn, Puma, ...) và thuê ở đâu cho hợp lý (DigitalOcean, Heroku, Amazon, ...) => So sánh, ưu nhược điểm của chúng
- Làm thế nào để tối ưu hóa SEO trên rails application. 
- Làm thế nào để tối ưu hóa source code, server để phục vụ nhiều người sử dụng nhất có thể. Giá phải trả cho việc tăng lượng đáp ứng người dùng tương ứng là bao nhiêu. 
- Chia sẻ một số kinh nghiệm khi bắt đầu deploy 1 ứng dụng rails lên server

Mặc dù trong quá trình tìm tòi nhưng kinh nghiệm vẫn chưa đủ, cảm thấy chúng là 1 trong những rào cản để đưa ứng dụng/startup của mình đến với người sử dụng.
Vậy mong những bạn, anh, chị có kinh nghiệm chia sẻ với mọi người thì tốt quá. Bạn nào chưa biết thì có thể học hỏi, bạn nào biết rồi thì trao đổi thêm với mọi người, giúp cộng đồng RoR chúng ta có nhiếu startup thành công trong tương lai. 
Cảm ơn mọi người.

Địa điểm: Hà Nội
Theo quan điểm của cá nhân thì cộng đồng RoR HN hoạt động có vẻ ít hơn HCM, hoặc hoạt động chìm quá. :)

**Comment by joneslee85** [comment]
@buithehien1991 tháng 1 thì đủ bài nói rồi, vậy thì để bài này tháng 3 đc không nhỉ?

**Comment by buithehien1991** [comment]
@joneslee85  Vâng ạ. Bài này em muốn anh chị nào đó nói ạ. Chứ em chưa đủ kinh nghiệm :)

**Comment by ghost** [comment]
Code 1 năm thì nói quá ngon rồi :dancer:  . Bạn không làm thì ai làm đây :+1:
