### ISSUE TITLE
Meetup 1/2016 - Kim Hiếu (@kimhieu) - Giới thiệu về Ruboto (Ruby for Android Dev)

### ISSUE THREAD

**Issue by trankimhieu** [ruby-vietnam/meetup#82]
Mình thấy có nhiều bạn dev backend rồi muốn chuyển qua frontend. Có 1 thư viện để viết Android bằng Ruby là `Roboto` nên mình xin có 1 bài nói 15p để giới thiệu về topic này.

Có thể sẽ ít người xài nó. Nhưng cũng thú vụ để viết những cái micro app tương tác với API mà không cần học ngôn ngữ khác.

**Comment by trankimhieu** [comment]
@joneslee85 Anh labeling giùm em với.

**Comment by joneslee85** [comment]
:+1:

**Comment by phongtattuan** [comment]
:+1:

**Comment by vinhnglx** [comment]
:+1:

**Comment by anhdayem818** [comment]
:+1:

**Comment by dathi** [comment]
:+1:

**Comment by thaod** [comment]
:+1:

**Comment by haidang30** [comment]
:+1:

**Comment by buithehoa** [comment]
:+1:

**Comment by huynhquancam** [comment]
:+1:

**Comment by tanngoc93** [comment]
:+1:

**Comment by hoang1417** [comment]
:+1:

**Comment by runlevel5** [comment]
@trankimhieu can you please update the post with slide URL?
