### ISSUE TITLE
Meetup ?/2016 - Ngoc Hai (@hoasung01) - Giới thiệu về Rasperry Pi nhúng Artoo (ruby framework)

### ISSUE THREAD

**Issue by hoasung01** [ruby-vietnam/meetup#84]
Hi mọi người,
- Sau một thời gian tìm hiểu mình muốn làm một presentation về những kiến thức cơ bản nhất về lập trình nhúng với rasperry pi.
- Mình sẽ giới thiệu qua về RasperryPi, Artoo framework được viết bằng ruby và demo chương trình bằng LED đơn giản.
- Ở buổi thuyết trình thì mình cần có màn hình, chuột và bàn phím để kết nối với board RasperryPi khi chạy chương trình demo.

**Comment by phongtattuan** [comment]
:+1:

**Comment by runlevel5** [comment]
:+1:

**Comment by vumanhcuongit** [comment]
:+1:

**Comment by giangstrider** [comment]
:+1:

**Comment by tranductam2802** [comment]
:+1: Hay quá anh ơi. Cái này anh có thể share với team ở Hà Nội không ạh?

**Comment by hoang1417** [comment]
:100: :+1:

**Comment by dieunb** [comment]
:+1:

**Comment by quocnv** [comment]
Hót rồi :D

**Comment by hoksilato** [comment]
:+1:

**Comment by tangten** [comment]
:+1:
