### ISSUE TITLE
Meetup 1/2016 - Trình Đức Duy (@duytd) - Làm quen với Apache Thrift

### ISSUE THREAD

**Issue by duytd** [ruby-vietnam/meetup#85]
Trong quá trình làm Rails mình có gặp phải một vấn đề, đó là phải tìm cách sử dụng thư viện của ngôn ngữ khác Ruby cho dự án. Sau một thời gian tìm hiểu, mình đã sử dụng Apache Thrift. Thấy nó khá thú vị nên mình muốn có một bài chia sẻ về chủ đề này.
- Độ dài: 15"  
- Địa điểm: Hà Nội

[meetup.pdf](https://github.com/ruby-vietnam/meetup/files/99266/meetup.pdf)

**Comment by hieuk09** [comment]
:+1:

**Comment by runlevel5** [comment]
nice nice +1

**Comment by minhdanh** [comment]
:+1:

**Comment by giangstrider** [comment]
:+1:

**Comment by nguyenducgiang** [comment]
:+1:

**Comment by huydx** [comment]
:+1:

**Comment by duytd** [comment]
Gửi mọi người slides bài nói nhé 
[meetup.pdf](https://github.com/ruby-vietnam/meetup/files/99266/meetup.pdf)
