### ISSUE TITLE
Meetup 3/2016 - Hiếu Nguyễn (@hieuk09) - Authenticate using Warden

### ISSUE THREAD

**Issue by hieuk09** [ruby-vietnam/meetup#86]
- Devise gives us a huge range of features and configuration, but sometimes really complicated and overkill for simple app.
- This talk will give you some ideas about how to create a simple authentication strategy with Warden.

Slide: http://www.slideshare.net/HieuNguyenTrung/introduce-warden

**Comment by huydx** [comment]
:+1:

**Comment by runlevel5** [comment]
:+1:

**Comment by hoksilato** [comment]
:+1:

**Comment by nguyenngoc2505** [comment]
:+1:

**Comment by mmeeoorroo** [comment]
:+1: dung cai minh dang can

**Comment by runlevel5** [comment]
@hieuk09 em có thể lấy một vd cho non-rails đc không nhỉ? vd trên hanami hay sinatra ấy

**Comment by nnluukhtn** [comment]
:+1:

**Comment by hieuk09** [comment]
@joneslee85 Em đang làm một cái với Hanami, nên chắc sẽ nói về sử dụng Warden trong Hanami và Rails. Sinatra thì chắc là lần khác :-?

**Comment by runlevel5** [comment]
vậy anh vote thêm :+1: nếu em cho xem ví dụ với hanami

**Comment by duytd** [comment]
:+1:

**Comment by longkt90** [comment]
:+1:

**Comment by tunglam14** [comment]
:+1:

**Comment by tangten** [comment]
:+1:

**Comment by nthngoc277** [comment]
:+1:

**Comment by hieuk09** [comment]
Slide: http://www.slideshare.net/HieuNguyenTrung/introduce-warden
