### ISSUE TITLE
Meetup 3/2016 - Kiên Nguyễn (@kiennt) - Secure your Login with facebook API

### ISSUE THREAD

**Issue by kiennt** [ruby-vietnam/meetup#87]
Sau một thời gian, trong quá trình làm việc và giúp đỡ các công ty build sản phẩm backend, mình nhận thấy rất nhiều công ty đã mắc lỗi bảo mật khi build API để login với facebook. 

Trong bài nói này, mình muốn chia sẻ những lỗi bảo mật có thể xảy ra khi xây dựng API login, và kêu gọi sự chú ý của cộng đồng để phổ biến best practice khi làm việc với Facebook API.

Slides: https://slidr.io/kiennt/securing-login-with-facebook-api-for-mobile-application

**Comment by huydx** [comment]
:+1: :+1: :+1: :+1: :+1: :+1:

**Comment by runlevel5** [comment]
:+1:

**Comment by hoksilato** [comment]
:+1:

**Comment by hieuk09** [comment]
:+1: Is this talk in Hanoi?

**Comment by karmiphuc** [comment]
:+1:

**Comment by kiennt** [comment]
@hieuk09  

This one is on HCMC, I already moved my family in HCMC.

**Comment by phongtattuan** [comment]
:+1:

**Comment by mmeeoorroo** [comment]
:+1:

**Comment by tucq88** [comment]
có stream hay skype để ae theo dõi được ko ?

**Comment by mymai91** [comment]
:+1:

**Comment by vinhnglx** [comment]
:+1:

**Comment by duytd** [comment]
:+1:

**Comment by longkt90** [comment]
:+1:

**Comment by nthngoc277** [comment]
:+1:

**Comment by dieunb** [comment]
:+1:
