### ISSUE TITLE
Meetup 3/2016 - Tiến An (@thiensubs) - ExecJS: Node.js vs RubyRacer (5')

### ISSUE THREAD

**Issue by thiensubs** [ruby-vietnam/meetup#89]
- ExecJS là gì? Mục đích? Sử dụng NodeJS và RubyRacer với Runtime JS
- Benchmark nho nhỏ.
- Một vài kết luận và thảo luận.

**Comment by runlevel5** [comment]
cảm ơn bạn, bài này dài bao nhiêu phút?

**Comment by thiensubs** [comment]
Bài này khoảng 5 phút nhé anh.

On Friday, 25 March 2016, Trung Lê notifications@github.com wrote:

> cảm ơn bạn, bài này dài bao nhiêu phút?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ruby-vietnam/meetup/issues/89#issuecomment-201178892

## 

_-----------------------------------------------------------------------Chào
thân ái và quyết thắng..._
_Trong đời có hàng trăm cái lý ngang với chân lý, nhưng chân lý là duy
nhất!_
Tiến An ^_^ BS  Phone: 0127.3851.881
