### ISSUE TITLE
Meetup ?/2016 - RubyMotion and write iOS native app with ruby (intro + demo)

### ISSUE THREAD

**Issue by dieunb** [ruby-vietnam/meetup#90]
[RubyMotion](http://www.rubymotion.com) một Ruby Implementation. Ra đời bản đầu tiên (1.0) từ năm 2012, giúp cho các lập trình viên Ruby viết ứng dụng iOS, OS X native. RubyMotion đã nhận được nhiều phản hồi tích cực từ cộng đồng các lập trình viên, cũng như phát triển ecosystem một nhanh với libraries, screencasts and books. Đến nay, bên cạnh hỗ trợ viết iOS, OS X native app, RubyMotion còn hỗ trợ viết android native app. 

Bài viết sẽ chia sẻ chi tiết thêm các thông tin về RubyMotion + Demo một ứng dụng iOS được viết hoàn toàn bằng Ruby.

**Comment by runlevel5** [comment]
:+1:
