### ISSUE TITLE
Meetup 3/2016, Tâm Phạm (@tampham47) - Frontend developer tại sao không?

### ISSUE THREAD

**Issue by tam-pham-alpha** [ruby-vietnam/meetup#91]
- Quan điểm về lập trình frontend trong cộng đồng lập trình viên.
- Vai trò của frontend developer trong nền công nghiệp phần mềm hiện đại.
- Làm thế nào để trở thành lập trình viên frontend.
# 

ps/ mình đăng ký hơi trễ, nên nếu đã hết xuất thì mình để dành tháng sau cũng được :))
# hcmc.rb, #7, #beginner.

**Comment by runlevel5** [comment]
cảm ơn bạn rất nhiều, mình tiếc là lần này full rồi, nên minh để lần sau nhé

**Comment by tam-pham-alpha** [comment]
Sẽ mở lại vào dịp khác :))
