### ISSUE TITLE
Meetup 08/2016 - @hieuk09 - Meta-programing in Ruby - Behind Rails Magic

### ISSUE THREAD

**Issue by hieuk09** [ruby-vietnam/meetup#94]
Rails has a lot of magic: autoload files/classes, auto-generate methods (`find_by_`, `find_and_initialize_by_`, ...). This talk intent to explain the mechanism behind theses magic (`const_missing`, `method_missing`, ...).

[Slide](http://www.slideshare.net/HieuNguyenTrung/metaprograming-rails-secret)

**Comment by runlevel5** [comment]
:+1:

**Comment by mymai91** [comment]
+1
