### ISSUE TITLE
Meetup 06/2016 - Mittosiro - Frontend get started

### ISSUE THREAD

**Issue by tam-pham-alpha** [ruby-vietnam/meetup#98]
- Boilerplate gulp-starter để bắt đầu làm giao diện
- Viết css theo chuẩn BEM
- Tự động hóa với npm scripts (nodejs)

Mình nói trong 7 phút nhé

**Comment by runlevel5** [comment]
:+1:

**Comment by mymai91** [comment]
+1

**Comment by giangstrider** [comment]
:+1: 4
