### ISSUE TITLE
Meetup 06/2016 - Cẩm Huỳnh - Summary of Reddot Ruby Conference 2016

### ISSUE THREAD

**Issue by qcam** [ruby-vietnam/meetup#99]
I will be doing up a quick summary of talks I loved at Reddot Ruby Conf 2016 (RDRC2016), e.g Matz's keynote about Ruby Typing, Jason Yeo talking about how to write a LISP in Ruby, etc.

**Comment by qcam** [comment]
Done

**Comment by hieuk09** [comment]
Do you have a slide for this talk? Could you share it here?

**Comment by qcam** [comment]
Here you are https://speakerdeck.com/hqc/reddit-ruby-conf-2016-recap
